### ISSUE TITLE
When changing or initially setting the timekeeper, system time is not synchronized to timekeeper time on PharLap until the system is rebooted

### ISSUE THREAD

**Issue by rtzoeller** [ni/niveristand-synchronization-custom-device#10]
When the timekeeper is changed in the system definition for PharLap targets, the change does not take effect upon deployment. Rebooting the target after the deployment will result in the correct synchronization occurring for future deployments (unless the timekeeper is changed again).

The timekeeper used by NI-TimeSync to drive the system time is read from a configuration file upon boot. The configuration file is updated to reflect the requested timekeeper upon deployment, but until the system is rebooted the previously configured timekeeper will be used.

This behavior is not described in the custom device.

**Comment by Karl-G1** [comment]
Pharlap support was dropped in #49. 
Closing this issue since we will not have Pharlap support in releases 21.0 and later.
