### ISSUE TITLE
PLL has lost phase-lock to the external reference clock - Error on Veristand

### ISSUE THREAD

**Issue by martincornejo** [ni/niveristand-synchronization-custom-device#47]
Hi,

We are using the custom device on multiple PXI-8880 controllers and 6683H timing cards on each. The timing custom device is added on Veristand and everything works as expected on most occasions. However, sometimes the deployment starts to fail continuously citing the PLL error as mentioned in the question title. Subsequent deployments work some times or they require a device reboot. 
We are using 1588 clock synchronisation and have only recently started experiencing this issue after 6 months of normal operation. I have attached the log file here for your reference. Could you maybe advice what might be causing this deployment error?

Regards,
Martin Cornejo
[Deploy Status.log](https://github.com/ni/niveristand-synchronization-custom-device/files/6862576/Deploy.Status.log)

**Comment by rtzoeller** [comment]
@martincornejo I am not aware of any issue specific to the custom device which could cause this behavior. I encourage you to reach out to NI Support directly, either at support@ni.com or +1(800) 531-5066; resolving this will likely require additional information and troubleshooting best handled outside of a GitHub issue.

**Comment by rtzoeller** [comment]
@martincornejo https://github.com/ni/niveristand-synchronization-custom-device/releases/tag/v21.0.1 should fix the issue you are seeing. Unfortunately it is only for VeriStand 2019 and newer, and limited to Linux RT controllers, as the 21.0.0 custom device releases have dropped support for PharLap like VeriStand 2021.

If you need a fix for PharLap or an older version of VeriStand, it may be possible to backport the changes and build it locally. https://github.com/ni/niveristand-synchronization-custom-device/commit/f5ce5558129dd9f4c76e1898515fd424a9059d0e contains the fix.

**Comment by rtzoeller** [comment]
I'm going to close this issue; if you need to backport the fix to VeriStand 2018 and run into issues, or the 21.0.1 custom device does not resolve the issue, feel free to open another.
